/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import utils.Fondo_Escritorio;

/**
 *
 * @author omar5
 */
public class Registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());
    Fondo_Escritorio escritorio = new Fondo_Escritorio();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new Fondo_Escritorio();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemAddEntre = new javax.swing.JMenu();
        itemAddInicio = new javax.swing.JMenuItem();
        itemAddFinal = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        itemAddEntre.setText("Opciones de registro");

        itemAddInicio.setText("Agregar al inicio");
        itemAddInicio.addActionListener(this::itemAddInicioActionPerformed);
        itemAddEntre.add(itemAddInicio);

        itemAddFinal.setText("Agregar al final");
        itemAddFinal.addActionListener(this::itemAddFinalActionPerformed);
        itemAddEntre.add(itemAddFinal);

        jMenuItem5.setText("Agregar entre nodos");
        itemAddEntre.add(jMenuItem5);

        jMenuBar1.add(itemAddEntre);

        jMenu2.setText("Buscar por ");

        jMenuItem3.setText("Registro civil");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Id representante");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Eliminar por");

        jMenuItem6.setText("Id de representante");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Registro civil");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAddInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAddInicioActionPerformed

    private void itemAddFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAddFinalActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemAddEntre;
    private javax.swing.JMenuItem itemAddFinal;
    private javax.swing.JMenuItem itemAddInicio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
